### ISSUE TITLE
Missing class in reports datatables (tbody tr) 

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#10220]
As you can see in the attached screenshot, the `<tr>` tag inside report's `<tbody>` datatable has no class, it's an empty space. `<tr class=" " [...]>`

That's causing issues on custom theming alternate rows in visitors datatables. No problems inside actions datatables ([forum topic about it](https://forum.piwik.org/t/theming-alternate-colors-in-table-rows/19647/1)) because of class definition: level0, level1, level3 ...

![istantanea_2016-06-07_14-11-50](https://cloud.githubusercontent.com/assets/92727/15857373/626a46b8-2cbb-11e6-96fd-450db46e55fc.png)

**Comment by tsteur** [comment]
I'm not quite sure, which class is missing here? Is the class actually needed in this case for alternate colors ? Does maybe using `tbody tr:nth-child(even) td { background-color: darken(@theme-color-background-tinyContrast, 10%) !important;}` work as well?

**Comment by tassoman** [comment]
Until now I've solved using this rules in my theme.less 

```css
table.dataTable tbody tr:nth-child(odd) td,
table.dataTable tbody tr.level0:nth-child(odd) td { background-color: @theme-color-background-tinyContrast !important; }
table.dataTable tbody tr.level1:nth-child(odd) td { background-color: darken(@theme-color-background-tinyContrast, 5%) !important; }
table.dataTable tbody tr.level2:nth-child(odd) td { background-color: darken(@theme-color-background-tinyContrast, 10%) !important; }
table.dataTable tbody tr.level3:nth-child(odd) td { background-color: darken(@theme-color-background-tinyContrast, 15%) !important; }
table.dataTable tbody tr.level4:nth-child(odd) td { background-color: darken(@theme-color-background-tinyContrast, 20%) !important; }
table.dataTable tbody tr.level5:nth-child(odd) td { background-color: darken(@theme-color-background-tinyContrast, 25%) !important; }
```
normal tr «oddity» takes @theme-color-background-tinyContrast then, going deeper in action tree datatable's rows you get 5 shades of grey 5% darker.

Rendered html by the browser draws `<tr class=" "`, doesn't create aesthetic problem but I don't think is strictly correct to declare empty arguments in html.
