### ISSUE TITLE
Nothing record.

### ISSUE THREAD

**Issue by chadyred** [piwik/piwik#12184]
Hello,

I have install piwik version 3.2 with docker-compose. Three different docker-compose have been use and always same result: 

Nothing seems record...

I have use this examples: 

- https://github.com/bitnami/bitnami-docker-piwik;
- https://github.com/indiehosters/piwik.

And all works fine but nothing is record. One simple example with bitnami :

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    networks:  # Les réseau sur lequel on se connect
      - default
  piwik:
    image: 'bitnami/piwik:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - VIRTUAL_HOST=piwik.dev
    depends_on:
      - mariadb
    volumes:
      - 'piwik_data:/bitnami'
    networks:  # Les réseau sur lequel on se connect
      - default
      - nginx-proxy
volumes:
  mariadb_data:
    driver: local
  piwik_data:
    driver: local
networks:
    nginx-proxy: # Nom du réseau externe créé à la main
        external:
            name: proxy-nginx
```

Then I have add website (idSite is 2) and I use JavaScript and it's send data : 

```
  <!-- Piwik -->
  <script type="text/javascript">
    var _paq = _paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="//piwik.dev/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '2']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <noscript><p><img src="//piwik.dev/piwik.php?idsite=2&rec=1" style="border:0;" alt="" /></p></noscript>
  <!-- End Piwik Code -->
```

Data is send by browser and are receive on my container. For all docker compose I have the same behavior:

```
piwik_1    | 172.18.0.3 - - [13/Oct/2017:05:51:39 +0000] "GET /piwik.php?action_name=my_site&idsite=2&rec=1&r=887751&h=7&m=51&s=39&url=http%3A%2F%2Fmy_site.dev%2Fprofile%2F&urlref=http%3A%2F%2Fmy_site.dev%2Frecette%2Fnew&_id=d6c860d631d25a0e&_idts=1507873767&_idvc=1&_idn=0&_refts=0&_viewts=1507873767&send_image=1&pdf=0&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=2560x1440&gt_ms=8101&pv_id=kNLa5M HTTP/1.1" 200 43
```

**Nothing is record...**

![image](https://user-images.githubusercontent.com/5954673/31532471-c2306274-afed-11e7-8c1a-fb1f0dabfa72.png)
