### ISSUE TITLE
[Bug] Visits in real-time widget filing with SQL error

### ISSUE THREAD

**Issue by Malcolm-GetAHead** [piwik/piwik#23171]
### What happened?

When visiting the main dashboard I receive the following error:

![Image](https://github.com/user-attachments/assets/f07116d9-8a0d-4770-bc53-b07b714d12b4)

The server request responds with a 500 error for this call, showing a database query issue:
```
2025/03/26 14:51:29 [error] 106#106: *284769 FastCGI sent in stderr: "PHP message: [mysite.example.com] Error in Matomo: Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;&#039; at line 1" while reading response header from upstream, client: 1.2.3.4, server: , request: "POST /index.php?date=yesterday&module=Live&action=widget&disableLink=0&widget=1&idSite=2&period=day HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mysite.example.com", referrer: "https://mysite.example.com/"
```

### What should happen?

Display the widget

### How can this be reproduced?

Default on-prem deployment, add a site, include the embedded JS code in a site.  We've done no real customization.

### Matomo version

5.3.0

### PHP version

8.3.15

### Server operating system

Docker

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 11 & MacOS

### Relevant log output

```shell

```

### Validations

- [x] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [x] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [x] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @Malcolm-GetAHead,

Sorry to hear you are having issues with the real-time report. Unfortunately it's hard to find the root cause for this without knowing the exact query that throws the error.
Are you maybe able to find that out by e.g. looking at database errors or similar?
I would assume it's caused by some of the tracked data, but without the affected query we can't easily fix that.
Thanks.

**Comment by Malcolm-GetAHead** [comment]
Hi @sgiehl ,

I've turned on the general query log and this is what I'm seeing when I open the specific page request:
```
MariaDB [mysql]> select * from general_log where user_host like '%matomo%' order by event_time desc limit 10\G
*************************** 1. row ***************************
  event_time: 2025-03-27 13:44:22.007740
   user_host: matomo[matomo] @  [10.98.0.194]
   thread_id: 109249
   server_id: 684935742
command_type: Query
    argument: select * from general_log where user_host like '%matomo%' order by event_time desc limit 10
*************************** 2. row ***************************
  event_time: 2025-03-27 13:44:19.847532
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Quit
    argument:
*************************** 3. row ***************************
  event_time: 2025-03-27 13:44:19.847467
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Close stmt
    argument:
*************************** 4. row ***************************
  event_time: 2025-03-27 13:44:19.840834
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Execute
    argument: INSERT INTO matomo_session (id,modified,lifetime,data) VALUES ###### truncated ######
*************************** 5. row ***************************
  event_time: 2025-03-27 13:44:19.840355
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Prepare
    argument: INSERT INTO matomo_session (id,modified,lifetime,data) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE modified = ?,lifetime = ?,data = ?
*************************** 6. row ***************************
  event_time: 2025-03-27 13:44:19.840235
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Close stmt
    argument:
*************************** 7. row ***************************
  event_time: 2025-03-27 13:44:19.839490
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Reset stmt
    argument:
*************************** 8. row ***************************
  event_time: 2025-03-27 13:44:19.839306
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Execute
    argument: SELECT option_value FROM `matomo_option` WHERE option_name = 'branding_use_custom_logo'
*************************** 9. row ***************************
  event_time: 2025-03-27 13:44:19.839195
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Prepare
    argument: SELECT option_value FROM `matomo_option` WHERE option_name = ?
*************************** 10. row ***************************
  event_time: 2025-03-27 13:44:19.838417
   user_host: matomo[matomo] @  [10.98.0.107]
   thread_id: 109526
   server_id: 684935742
command_type: Close stmt
    argument:
10 rows in set (0.174 sec)
```

I'm not seeing anything too specific here.  Can you suggest anything to gather more verbose logs?

Thanks
