### ISSUE TITLE
When one datatable label is very long it causes the table to stretch overlapping other reports

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#6121]
There's a problem with cells containing too much characters, they make widgets overlap each others.
As you can see in this [screenshot](http://imgur.com/9sO7KTU) the widget on the right overlaps the one on the left that's tooooo wiiiide because of content (AAAAAAAAAAAAAAAAA).

The same happens also in _Page Titles_ cells when you try to _make it flat_ the page goes horizontal, also.

Would be nice some kind of scrollable thing like "sliding doors" behavior. For now I've found this [stackOverflow answer](http://stackoverflow.com/questions/14492088/horizontal-scroll-in-table-cell)

I'm posting a screenshot taken with Firefox on Xubuntu, IE11+win7 behavior is the same.

![screenshot-demo piwik org 2016-06-07 12-08-32](https://cloud.githubusercontent.com/assets/92727/15854613/0e149a92-2cab-11e6-9521-6cb1275380b5.png)

**Comment by mattab** [comment]
@mnapoli  maybe this bug would also be solved with #7504 ?

**Comment by mnapoli** [comment]
Mmh I don't think so, the responsive thing should make one column go below the other when the window width is below a threshold. But in the case here it's a problem of overflow-x I guess (i.e. the table and its content span over the column width which is 50% of the screen). It might be easy to fix though, we could move it to 2.13 and I can give it a try?

I think however that #7504 will improve the situation in smaller screens (which is where this bug must appear the most).

**Comment by tassoman** [comment]
I've temporally solved this issue using a Theme. Inside theme.less I've added this CSS code:

```css
tr.level0 td.label {
  overflow: hidden;
  max-width: 1200px;
}
@media screen and (max-width: 1280px) {
  tr.level0 td.label {
    max-width: 700px;
  }
}
@media screen and (max-width: 1024px) {
  tr.level0 td.label {
    max-width: 350px;
  }
}
```
It tries to arbitrarily adapt cell with in different screen sizes.
